# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\chooseclassesform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChooseClasses(QtWidgets.QWidget):
    def __init__(self):
        super(Ui_ChooseClasses, self).__init__()
        self.setupUi(self)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(773, 488)
        Form.setStyleSheet("QWidget{background-color: rgb(57, 167, 255);border-radius:5px;}")
        Form.setWindowFlags(Qt.Qt.FramelessWindowHint | Qt.Qt.WindowStaysOnTopHint | Qt.Qt.Tool)
        Form.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 761, 431))
        font = QtGui.QFont()
        font.setFamily("汉仪文黑-85W")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setAutoScrollMargin(16)
        self.listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget.setProperty("isWrapping", True)
        self.listWidget.setWordWrap(False)
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("汉仪文黑-85W")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(680, 0, 93, 28))
        font = QtGui.QFont()
        font.setFamily("汉仪文黑-85W")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(".QPushButton{background-color:rgb(255, 255, 255);border: 1px solid #000;}.QPushButton:pressed{background-color: aqua;}\n"
"")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(self.exlse)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "请选择班级"))
        self.pushButton.setText(_translate("Form", "取消"))
    def exlse(self):
        self.close()
        loginui.hide()
